# Generated by Django 5.0.2 on 2024-03-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_category_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
