# Generated by Django 5.0.2 on 2024-03-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_num_in_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_imgaes')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_in_cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='num_in_cart',
        ),
    ]
