# Generated by Django 5.0.2 on 2024-03-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_carts_remove_item_is_in_cart_remove_item_num_in_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
        migrations.AddField(
            model_name='item',
            name='is_in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
